### ISSUE TITLE
Plain Xd6 roll

### ISSUE THREAD

**Issue by Lurius** [winks-vtt/yze-coriolis#1]
It would be really nice to have a button/something on the char sheet that could be used to make a plain "Coriolis" roll (=only 6s count). There could be situations where GM/player needs to just roll the dice and count the sixes. Not sure what the max amount of dice would be tho.

**Comment by AlexOkafor** [comment]
@Lurius  Ah yes, you're right. Given the flexibility of that, I do think this would be better as a macro(s) I include in the system. So players and GMs can just drag into into their macro bar as needed. I'll look into it. For the moment the work around is to do the manual rolls in chat `/roll Xd6`.
