### ISSUE TITLE
Rewrite experience handling

### ISSUE THREAD

**Issue by taranion** [winks-vtt/yze-coriolis#102]
Currently experience is another energy bar that has a maximum of 10.
This is neither suitable for tracking total experience, nor unused experience, since you can sum up more than 10 free exp,

Perhaps 2 numbers (free / total ) may be better than the energy bar.

**Comment by IrishWolf** [comment]
I thought about it, cause one of my players had the same problem (more than 10 exp acuumulated).

Changing that is easy but 10 numbers may be a bit tricky. In one row there isn't enough space for the explanations:
![image](https://user-images.githubusercontent.com/36819852/169132330-ced7a548-223a-4996-960a-d405f6912e92.png)

And with two rows it looks a bit bloated:
![image](https://user-images.githubusercontent.com/36819852/169135692-a366c2bb-592b-4740-8fe7-762c8ab9c258.png)

So I think the best is to just track the free Exp and not the max?
