### ISSUE TITLE
The file spaceship-keyart.svg breaks the Token Layer of the canvas in Firefox, rendering a Scene entirely broken.

### ISSUE THREAD

**Issue by grungydan** [winks-vtt/yze-coriolis#125]
In Firefox, dragging the file `yzecoriolis/css/icons/spaceship-keyart.svg` , which is used for the "generic/unnamed" ships in the Actors tab of Foundry, throws the following errors and breaks the entire Scene as the Token Layer cannot be drawn. 

`Error: Invalid BaseTexture systems/yzecoriolis/css/icons/spaceship-keyart.svg`
& subsequently 
`TypeError: Failed to render WebGL canvas: this.icon is undefined`

From the Forge devs while troubleshooting with them: 

> That error (the invalid base texture one) is one we've seen before on Firefox specifically which fails to load some svg images. There is no solution to that, other than the module creator being notified and regenerating the svg to not use something that Firefox doesn't support.

And from the Foundry VTT Media Optimization Guide: https://foundryvtt.com/article/media/

> For images which do not require a lot of visual complexity, SVG can also be used which will feature tiny file-sizes, support for transparency, can be easily animated, and can be scaled to any size without noticeable loss of quality. Consider using SVGs if you are making tiles, tokens, or icons for use in foundry that would benefit from transparency and scaling, but do not require extremely complex colour depth and detail.
> 
>In order to use a SVG image on a WebGL canvas, the SVG document must be given an explicit default width and height in its markup, for example:  
>  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">`

**Comment by AlexOkafor** [comment]
https://github.com/winks-vtt/yze-coriolis/pull/158
