### ISSUE TITLE
Pray to the Icons - Only dices not showing sixes

### ISSUE THREAD

**Issue by xenexelen** [winks-vtt/yze-coriolis#127]
"Pray to the Icons" is not a complete throw repeat. But, for example, if I do a trial with 7 dice and get 2 successes, then select "Pray to the Icons", all the dice are re-rolled. In this case, however, 5 dice would have to be rerolled and the previous 2 successes added up.

At least this is what I can gather from the English (and likewise the German) rules:

_"This means you get to reroll all dice not showing sixes... but you could pray even if there were sixes in your initial roll, to get more sixes and unlock more bonus effects."_

**Comment by AlexOkafor** [comment]
I'm assuming you're using Dice so nice? Visually it looks like all are being re-rolled with that plugin, but actually only the non-successes are.

**Comment by xenexelen** [comment]
Yes, I must apologize, it really was "Dice so nice". I will now disable the module in my rounds.
