### ISSUE TITLE
[BUG] Sheet registration fails if a module uses the new sheet registration method

### ISSUE THREAD

**Issue by kristianserrano** [winks-vtt/yze-coriolis#139]
Details can be found in [this Discord discussion](https://discord.com/channels/170995199584108546/722566083499786352/939550549001531452).

The system registers a sheet using a deprecated method. Atropos has confirmed that if _anything else_ uses the new method, the old method won't work.

The issue is with [this code](
https://github.com/winks-vtt/yze-coriolis/blob/5b574f5f585702947ac84355e7412d5f13a5d854/module/yzecoriolis.js#L50-L58).

Ideally, the code could do a [version check](https://foundryvtt.com/api/module-helpers.html#.isNewerVersion) on the Foundry instance and use the new method, and fall back to the old method if the version number is less than v9.

**Comment by AlexOkafor** [comment]
@kristianserrano Thanks for the heads up! Since the last version set the minimum to v9, I went ahead and started using the new API for journal registration.

**Comment by kristianserrano** [comment]
Thank you!
