### ISSUE TITLE
Create an NPC Sheet

### ISSUE THREAD

**Issue by AlexOkafor** [winks-vtt/yze-coriolis#14]
It'll be identical to a PC sheet for now except validation for skills will be higher and/or lifted.

**Comment by r-valyar** [comment]
Suggestion: After some dry-runs I recommend the NPCs sheet to be simplified and use the screen real estate much better. Maybe condensed layout with Attributes, Skills and Items on the same page to save time during combat with a lot of NPCs. Sliders for HP/MP/RAD can be simplified as well.

**Comment by AlexOkafor** [comment]
@r-valyar I think that's a good idea, and I have a note to address that in a future update. But for now, to smooth over some limitations with creating NPCs (particular with the official scenarios), I'm keeping the sheets identical except for disabling the capping of attributes and skills.
