### ISSUE TITLE
Add "Carry" toggle to Gear List

### ISSUE THREAD

**Issue by mrg67** [winks-vtt/yze-coriolis#142]
For the purposes of calculating encumbrance in the Items tab of an actor sheet, add a "carry" icon for each item.  This allows you to have items in your possession, but not have them on your person at all times.  Each item would have 3 possible "states":
1. Not carried, Not equipped (NOT part of encumbrance calculation)
2. Carried, Not equipped (part of encumbrance calculation)
3. Carried, Equipped (part of encumbrance calculation)

![image](https://user-images.githubusercontent.com/74210758/159046123-893ae2c9-53a1-4af0-87d8-a8d56cf5866c.png)

The other option is simply to keep the Equip toggle (the shield), but not include un-equipped items against encumbrance.

![image](https://user-images.githubusercontent.com/74210758/159047334-620a6733-db03-4dbe-8506-920acef8d2f2.png)

**Comment by mrg67** [comment]
Sorry.  Just noticed that this has already been requested in Issue #28 .

**Comment by AlexOkafor** [comment]
duplicate
