### ISSUE TITLE
Character artwork display not working

### ISSUE THREAD

**Issue by JCartaxo** [winks-vtt/yze-coriolis#148]
When the character artwork display is chosen, it shows the token artwork instead of the character artwork.

![image](https://user-images.githubusercontent.com/18288055/163041501-7c30d53a-ba25-4ae8-8889-5748b8ef082c.png)

**Comment by AtraAngelis** [comment]
This is a huge one, This is also broken for Ships. Character artwork and token are the same link in the code.

**Comment by AtraAngelis** [comment]
![ship](https://user-images.githubusercontent.com/98035055/168696654-2cd571e8-0d58-4985-a5b9-1a7c445471a8.PNG)

On the left is get Token Artwork, on the right is get Character Artwork, they both point to the tokens!

**Comment by AtraAngelis** [comment]
Not stale, still awaiting fix.

**Comment by coderunner** [comment]
@AtraAngelis @JCartaxo This is fixed in the latest release.

**Comment by coderunner** [comment]
@AlexOkafor Fixed also.
