### ISSUE TITLE
Rolling with negative modifier where dice number is 0 or negative rolls 2

### ISSUE THREAD

**Issue by Necrot1c** [winks-vtt/yze-coriolis#16]
Found a weird one, if you roll a skill and apply a negative modifier that would take the number of dice to 0 or a negative value 2 dice will be rolled.

**Comment by AlexOkafor** [comment]
@Necrot1c This is actually a rule from the core rulebook. I missed it on my first pass of the system and then discovered it (page 59 - zero dice). The system currently recognizes that and also requires both to be successes to turn up a 'success'.

**Comment by AlexOkafor** [comment]
Feel free to re-open if I mis-understood the context.
