### ISSUE TITLE
Item configuration

### ISSUE THREAD

**Issue by mrg67** [winks-vtt/yze-coriolis#160]
Similar to the attached screenshot of the Forbidden Lands system, allow Items to be configured beyond just modifying Hit Points and/or Mind Points.  Any item, whether it's a Talent, or weapon, or armor, etc., should be configurable to add modifiers to (or based on) any attribute, skill, talent, etc.

The modifiers defined for these items should only take effect when the item is ACTIVE or EQUIPPED.

![image](https://user-images.githubusercontent.com/74210758/168690104-82c3bead-8184-400e-82cc-8b0b238e6c99.png)

**Comment by AlexOkafor** [comment]
This has two major aspects to it before it is useful to players at large:
1. creating a system that can use this
2. updating nearly 500 items in the official content modules to utilize this
