### ISSUE TITLE
[Enhancement Request] Show weapon-features with attack-rolls?

### ISSUE THREAD

**Issue by kagedansa** [winks-vtt/yze-coriolis#190]
Would it be possible to display the characteristics of weapons on a dice roll? This would be helpful for the gamemaster, especially if the weapon is armor piercing.

**Comment by IrishWolf** [comment]
That is already possible.
If it isn't activated look at the system-settings :)

![image](https://user-images.githubusercontent.com/36819852/186646696-ff740198-74c4-4552-8a9d-1355afbf7102.png)
