### ISSUE TITLE
[Enhancement Request] Roll ship weapons like character weapons?

### ISSUE THREAD

**Issue by kagedansa** [winks-vtt/yze-coriolis#191]
Would it be possible to directly roll ship weapons with all values, analogous to the dice rolls for characters?

**Comment by kagedansa** [comment]
still a request

**Comment by kagedansa** [comment]
still a request

**Comment by kbender84** [comment]
Hi, I am creating Coriolis TokenActionHud and this feature should be implemented in my modlue soon.
