### ISSUE TITLE
Actor sheets not working

### ISSUE THREAD

**Issue by Johan1283** [winks-vtt/yze-coriolis#202]
I can't open actor sheets. Neither can I edit item sheets. It still works in a different game system, so it's not FoundryVTT that is the problem. With or without modules active, however I try to open the actor sheet, nothing happens. I can create new actors, just not edit them. 
Any help would be appreciated.

**Comment by AlexOkafor** [comment]
@Johan1283 Which version of Foundry are you currently running?

**Comment by Johan1283** [comment]
Thanks for replying!
Currently v.10 build 284. I'll try v9 and see if it fixes the problem.

**Comment by AlexOkafor** [comment]
Just verified on my end while updating to v10 compatbility that this is just an issue with v9 data in v10. Should work once i get a v10 update out next week.
