### ISSUE TITLE
[Enhancement request] Use targeting function to further streamline combat

### ISSUE THREAD

**Issue by TheHerugrim** [winks-vtt/yze-coriolis#213]
Is it possible to make use of the targeting function to streamline some of the combat flow?

For example:
Select your token.
Target enemy token.
Roll to attack with your pistol.
On a success, it prompts the armor/protection roll of the targeted token in chat.
After the armor roll, it allows you to "apply damage" and calculates damage according to its result, maybe with an option to type in how many of the additional successes from an attack are put towards additional damage/stress when rolling for armor.

Or something along those lines.
Love the rest of the system!

**Comment by AlexOkafor** [comment]
It's something I would like to add, but don't have the spare cycles to dig into at the moment. This may be something one of the other contributor may be able to pick up?
