### ISSUE TITLE
Dragging crew to ship not working

### ISSUE THREAD

**Issue by dutchcolonial** [winks-vtt/yze-coriolis#222]
I can't drag and drop crew (Actors) to the crew section of the ship.
The actors all have roles assigned but when I drag them to the crew section nothing happens. I openend the console (F12) and dragging and dropping does not invoke anything.

**Comment by IrishWolf** [comment]
The sheet don't assign the crew via drag and drop.

You must open the actor-sheets and under "Bio" you can choose the ship and position.

**Comment by dutchcolonial** [comment]
Oh, okay, but that doesn't seem to work either:
[image: image.png]


How does it match the selection in the screenshot with the ship/actor?

**Comment by IrishWolf** [comment]
It should actually work that way.

Is your Foundry and Coriolis-Module on the latest version?
For example, if you have still foundry v9 but the latest coriolis-sheet it won't work properly.

**Comment by dutchcolonial** [comment]
Foundry version 10 build 291
I just installed Coriolis system andmodules yesterday evening, so I assume it is up to date.

**Comment by dutchcolonial** [comment]
Okay, I found the issue. If I make a copy of the original Scarab ship (and remove the text (Copy) ) then it doesn't work.
The crew member does show up in the original ship that came with the module.
That seems weird. How is the link established between the crew member and the ship?

**Comment by IrishWolf** [comment]
They are linked via the (not usually visible) ID of the actors and the ship.

So if you have two Ships with the same name, the ship should be two times in the list and an actor who is assigned to one ship won't show up to the other.
But for the best result you shouldn't name two ships the same.

**Comment by dutchcolonial** [comment]
Great, thanks, I have it all working. Thanks for the help. this can be closed.

**Comment by AlexOkafor** [comment]
Thanks for looking into this @IrishWolf !
