### ISSUE TITLE
Encumbrance is not calculated properly

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#23]
The current formula for encumbrance is Strength x4, while the game rules state:   **Generally, you can carry a number of items equal to your Strength doubled.**

**Comment by AlexOkafor** [comment]
I think I'll have to change the display for the encumbrance meter to be in line with the rules. To avoid fractional slots (and the headaches that can bring) I had doubled everything internally so that a 'half slot' is 1. So a heavy item takes up 2x than normal, etc.
