### ISSUE TITLE
Praying to the Icons Rerolls All Dice

### ISSUE THREAD

**Issue by JTThurn** [winks-vtt/yze-coriolis#231]
G'day!

Something that has changed since pre-3.0.5: praying to an icon rerolls _all_ dice rather than just the unsuccessful ones.

**Comment by IrishWolf** [comment]
> Something that has changed since pre-3.0.5: praying to an icon rerolls _all_ dice rather than just the unsuccessful ones.

I tested it right now (and in my last session last Saturday) and everything is as it should.
Coriolis 3.0.12 installed with Foundry 10.291.

Which Foundry-Version do you have installed?
Can you make a short video/screen-capture of the problem?

And just pro forma:
Don't look at Dice so nice-animations. They just show you every dice as rolled but that has nothing to do with the real roll of Foundry.

**Comment by JTThurn** [comment]
Sooooo I found the problem. I'm an idiot. (That's both the short and long version.)

Future best practice: ignore me in every instance.
