### ISSUE TITLE
update to core system to include rollItemMacro

### ISSUE THREAD

**Issue by kbender84** [winks-vtt/yze-coriolis#232]
I've developed token-action-hud for Coriolis, but to work properly it requires additional functions in yzecoriolis.js and actor.js
I have the code, can it be added to the new release of the core system?

**Comment by kbender84** [comment]
//yzecoriolis.js

// Import Modules
import { YZECORIOLIS } from "./config.js";
import { registerSystemSettings } from "./settings.js";
import { yzecoriolisActor } from "./actor/actor.js";
import { yzecoriolisActorSheet } from "./actor/actor-sheet.js";
import { yzecoriolisShipSheet } from "./actor/ship-sheet.js";
import { yzecoriolisItem } from "./item/item.js";
import { yzecoriolisItemSheet } from "./item/item-sheet.js";
import { coriolisChatListeners } from "./coriolis-roll.js";
import {
  getAttributeKeyForWeaponType,
  getSkillKeyForWeaponType,
} from "./item/item.js";
import * as migrations from "./migration.js";
import { preloadHandlerbarsTemplates } from "./templates.js";
import {
  addDarknessPoints,
  spendDarknessPoints,
  displayDarknessPoints,
} from "./darkness-points.js";
import { getActorDataById } from "./util.js";
import {
  importShipSheetTutorial,
  showOnboardingMessage,
} from "./onboarding.js";
import { coriolisJournalSheet } from "./coriolisJournal.js";

Hooks.once("init", async function () {
  console.log(`Coriolis | Initializing Coriolis\n${YZECORIOLIS.ASCII}`);
  game.yzecoriolis = {
    yzecoriolisActor,
    yzecoriolisItem,
    rollItemMacro,
    **rollActorMacro**,
    config: YZECORIOLIS,
    migrations: migrations,
  };

  // Setup TinyMCE stylings
  CONFIG.TinyMCE.content_css = "systems/yzecoriolis/css/yzecoriolismce.css";

  DocumentSheetConfig.registerSheet(
    JournalEntry,
    "yzecoriolis",
    coriolisJournalSheet,
    { makeDefault: true }
  );

  preloadHandlerbarsTemplates();

  // Define custom Entity classes
  CONFIG.Actor.documentClass = yzecoriolisActor;
  CONFIG.Item.documentClass = yzecoriolisItem;
  CONFIG.YZECORIOLIS = YZECORIOLIS;

  //Register system settings
  registerSystemSettings();

  // Register sheet application classes
  Actors.unregisterSheet("core", ActorSheet);
  Actors.registerSheet("yzecoriolis", yzecoriolisActorSheet, {
    types: ["character"],
    makeDefault: true,
    label: "YZECORIOLIS.SheetClassCharacter",
  });
  Actors.registerSheet("yzecoriolis", yzecoriolisActorSheet, {
    types: ["npc"],
    makeDefault: true,
    label: "YZECORIOLIS.SheetClassNPC",
  });
  Actors.registerSheet("yzecoriolis", yzecoriolisShipSheet, {
    types: ["ship"],
    makeDefault: true,
    label: "YZECORIOLIS.SheetClassShip",
  });

  Items.unregisterSheet("core", ItemSheet);
  Items.registerSheet("yzecoriolis", yzecoriolisItemSheet, {
    makeDefault: true,
    label: "SheetClassItem",
  });

  /**
   * Set an initiative formula for the system
   * @type {String}
   */
  CONFIG.Combat.initiative = {
    formula: "1d6+(1d6*0.1)",
    decimals: 1,
  };

  // register turn order changes. Currently it's sorting from high->low so no need to edit atm.
  //Combat.prototype.setupTurns = setupCoriolisTurns;

  Handlebars.registerHelper("concat", function () {
    var outStr = "";
    for (var arg in arguments) {
      if (typeof arguments[arg] != "object") {
        outStr += arguments[arg];
      }
    }
    return outStr;
  });

  Handlebars.registerHelper("toLowerCase", function (str) {
    return str.toLowerCase();
  });

  Handlebars.registerHelper("if_eq", function (a, b, opts) {
    if (a === b) {
      return opts.fn(this);
    } else {
      return opts.inverse(this);
    }
  });

  Handlebars.registerHelper("if_gt", function (a, b, opts) {
    if (a > b) {
      return opts.fn(this);
    } else {
      return opts.inverse(this);
    }
  });

  Handlebars.registerHelper("if_notEmptyString", function (a, opts) {
    if (a !== "") {
      return opts.fn(this);
    } else {
      return opts.inverse(this);
    }
  });

  Handlebars.registerHelper("getSkillName", function (skillkey) {
    return CONFIG.YZECORIOLIS.skills[skillkey];
  });
  Handlebars.registerHelper("getSkillRollName", function (skillkey) {
    return CONFIG.YZECORIOLIS.skillRolls[skillkey];
  });

  Handlebars.registerHelper("getSkillCategoryName", function (skillkey) {
    return CONFIG.YZECORIOLIS.skillCategories[skillkey];
  });

  Handlebars.registerHelper("getAttributeName", function (attributeKey) {
    return CONFIG.YZECORIOLIS.attributes[attributeKey];
  });

  Handlebars.registerHelper("getAttributeRollName", function (attributeKey) {
    return CONFIG.YZECORIOLIS.attributeRolls[attributeKey];
  });

  Handlebars.registerHelper("getItemTypeName", function (itemTypeKey) {
    return CONFIG.YZECORIOLIS.itemTypes[itemTypeKey];
  });

  Handlebars.registerHelper(
    "getTalentCategoryName",
    function (talentCategoryKey) {
      return CONFIG.YZECORIOLIS.talentCategories[talentCategoryKey];
    }
  );

  Handlebars.registerHelper("getGearWeightName", function (gearWeight) {
    return CONFIG.YZECORIOLIS.gearWeights[gearWeight];
  });

  Handlebars.registerHelper("getGearName", function (gearName) {
    return CONFIG.YZECORIOLIS.gearNames[gearName];
  });

  Handlebars.registerHelper("getTechTierName", function (tier) {
    return CONFIG.YZECORIOLIS.techTiers[tier];
  });

  Handlebars.registerHelper("getWeightName", function (weight) {
    return CONFIG.YZECORIOLIS.gearWeights[weight];
  });

  Handlebars.registerHelper("getRangeName", function (range) {
    return CONFIG.YZECORIOLIS.ranges[range];
  });

  Handlebars.registerHelper("getShipRangeName", function (range) {
    return CONFIG.YZECORIOLIS.shipWeaponRanges[range];
  });

  Handlebars.registerHelper("getWeaponCritDisplay", function (critObj) {
    if (critObj.numericValue > 0 && critObj.customValue !== "") {
      return `${critObj.numericValue}/${critObj.customValue}`;
    }
    if (critObj.numericValue > 0) {
      return `${critObj.numericValue}`;
    }
    if (critObj.customValue !== "") {
      return `${critObj.customValue}`;
    }
    return "";
  });

  Handlebars.registerHelper("percentcss", function (a, b) {
    if (b <= 0) {
      return 0;
    }
    return (a / b) * 100;
  });

  Handlebars.registerHelper("talentHasCost", function (talentCategory, opts) {
    if (talentCategory === "cybernetic" || talentCategory === "bionicsculpt") {
      return opts.fn(this);
    } else {
      return opts.inverse(this);
    }
  });

  Handlebars.registerHelper("getSkillKeyForWeaponType", function (isMelee) {
    return getSkillKeyForWeaponType(isMelee);
  });

  Handlebars.registerHelper("getAttributeKeyForWeaponType", function (isMelee) {
    return getAttributeKeyForWeaponType(isMelee);
  });

  // returns just the position without the ship name.
  Handlebars.registerHelper(
    "getCrewPositionNameBasic",
    function (crewPosition) {
      let positionName =
        CONFIG.YZECORIOLIS.crewPositions[crewPosition.position];
      // for non associated crew, just return position name
      if (!crewPosition.shipId) {
        return positionName;
      }
      // search for ship and grab "ship - crewPosition"
      let ship = game.actors.get(crewPosition.shipId);
      if (!ship) {
        console.warn("failed to find ship", crewPosition);
        return positionName;
      }
      return `${positionName}`;
    }
  );

  Handlebars.registerHelper(
    "getShipRollNameForPosition",
    function (crewPosition) {
      const skill = CONFIG.YZECORIOLIS.crewRolls[crewPosition.position];
      return CONFIG.YZECORIOLIS.skills[skill];
    }
  );

  Handlebars.registerHelper("getShipRollValueForPosition", function (crewId) {
    const crew = getActorDataById(crewId);
    const crewPosition = crew.system.bio.crewPosition;
    const skillKey = CONFIG.YZECORIOLIS.crewRolls[crewPosition.position];
    const skillValue = crew.system.skills[skillKey].value;
    const attribKey = crew.system.skills[skillKey].attribute;
    const attribValue = crew.system.attributes[attribKey].value;
    return attribValue + skillValue;
  });

  Handlebars.registerHelper("isNotEmpty", (obj) => {
    return Object.keys(obj).length > 0;
  });

  Handlebars.registerHelper("ShowFeatures", function () {
    return game.settings.get("yzecoriolis", "AlwaysShowFeatures");
  });

  Handlebars.registerHelper("AdditionalRollInfos", function () {
    return game.settings.get("yzecoriolis", "AdditionalRollInfos");
  });
});

// called after game data is loaded from severs. entities exist
Hooks.once("setup", function () {
  // Localize CONFIG objects once up-front
  const toLocalize = [
    "attributes",
    "attributeRolls",
    "skillCategories",
    "skills",
    "skillRolls",
    "talentCategories",
    "talentGroupConceptCategories",
    "talents",
    "techTiers",
    "gearWeights",
    "critTypes",
    "ranges",
    "icons",
    "crewPositions",
    "shipModuleCategories",
    "shipWeaponRanges",
  ];

  // exclude sorting from some config values where the order matters.
  const noSort = [
    "talentCategories",
    "shipModuleCategories",
    "techTiers",
    "gearWeights",
    "critTypes",
    "ranges",
    "icons",
    "shipWeaponRanges",
  ];

  for (let o of toLocalize) {
    const localized = Object.entries(CONFIG.YZECORIOLIS[o]).map((e) => {
      return [e[0], game.i18n.localize(e[1])];
    });
    if (!noSort.includes(o)) localized.sort((a, b) => a[1].localeCompare(b[1]));
    CONFIG.YZECORIOLIS[o] = localized.reduce((obj, e) => {
      obj[e[0]] = e[1];
      return obj;
    }, {});
  }
});

// Activate chat listeners for coriolis
// eslint-disable-next-line no-unused-vars
Hooks.on("renderChatLog", (log, html, data) => {
  coriolisChatListeners(html);
});

Hooks.on("renderChatMessage", (app, html, msg) => {
  // Do not display "Blind" chat cards to non-gm
  if (html.hasClass("blind") && !game.user.isGM) {
    // since the header has timestamp content we'll remove the content instead.
    // this avoids an NPE when foundry tries to update the timestamps.
    html.find(".message-content").remove();
  }
  // remove push option from non-authors
  if (!game.user.isGM && msg.message.user !== game.user.id) {
    html.find(".dice-push").remove();
  }
});

Hooks.on("getSceneControlButtons", (controls) => {
  let group = controls.find((b) => b.name == "token");
  group.tools.push(
    {
      name: "add",
      title: "YZECORIOLIS.DarknessPointsAdd",
      icon: "fas fa-plus",
      buttons: true,
      visible: game.user.isGM,
      onClick: () => {
        addDarknessPoints(1);
      },
    },
    {
      name: "substract",
      title: "YZECORIOLIS.DarknessPointsRemove",
      icon: "fas fa-minus",
      buttons: true,
      visible: game.user.isGM,
      onClick: () => {
        spendDarknessPoints(1);
      },
    },
    {
      name: "inspect",
      title: "YZECORIOLIS.DarknessPoints",
      icon: "fas fa-question",
      buttons: true,
      visible: game.user.isGM,
      onClick: () => {
        displayDarknessPoints();
      },
    }
  );
});

Hooks.once("ready", async function () {
  // Determine whether a system migration is required and feasible
  const currentVersion = game.settings.get(
    "yzecoriolis",
    "systemMigrationVersion"
  );
  const NEEDS_MIGRATION_VERSION = "2.5.0";
  const COMPATIBLE_MIGRATION_VERSION = "1.4.7";
  let needMigration =
    currentVersion &&
    isNewerVersion(NEEDS_MIGRATION_VERSION, currentVersion) &&
    currentVersion !== "0"; // zero means we just created a new world.

  // Perform the migration
  if (needMigration && game.user.isGM) {
    if (
      currentVersion &&
      isNewerVersion(COMPATIBLE_MIGRATION_VERSION, currentVersion)
    ) {
      ui.notifications.error(game.i18n.localize("ErrorsOldFoundryVersion"), {
        permanent: true,
      });
    }
    await migrations.migrateWorld();
  }
  //bootstrapTalentCompendium();
  //bootstrapGearCompendium();

  // wait to register hotbar drop hook on ready so that modules could register earlier if they want to
  Hooks.on("hotbarDrop", (bar, data, slot) => {
    createYzeCoriolisMacro(data, slot);
    if (data.type === "Item") {
      return false;
    }
  });

  await importShipSheetTutorial();
  await showOnboardingMessage();
});

Hooks.once("diceSoNiceReady", (dice3d) => {
  dice3d.addSystem(
    { id: "yzecoriolis", name: "Coriolis: Third Horizon" },
    true
  );
  dice3d.addDicePreset({
    type: "d6",
    labels: [
      "systems/yzecoriolis/css/images/dice-1.png",
      "systems/yzecoriolis/css/images/dice-2.png",
      "systems/yzecoriolis/css/images/dice-3.png",
      "systems/yzecoriolis/css/images/dice-4.png",
      "systems/yzecoriolis/css/images/dice-5.png",
      "systems/yzecoriolis/css/images/dice-6.png",
    ],
    // bumpMaps: [, , , , , , , , , , , , , , , , , , ,
    //   "systems/archmage/images/nat20_BUMP.png"
    // ],
    system: "yzecoriolis",
  });
  dice3d.addColorset(
    {
      name: "yzecoriolis",
      description: "Coriolis Third Horizon",
      category: "Colors",
      foreground: "#FFFFFF",
      background: "#000000",
      outline: "gray",
      texture: "none",
    },
    "force"
  );
});

/**
 * Create a macro from an Item drop
 * @param  {} documentData
 * @param  {} slot
 */
async function createYzeCoriolisMacro(documentData, slot) {
  if (documentData.type !== "Item") return;
  if (!("uuid" in documentData))
    return ui.notifications.warn(
      game.i18n.localize("YZECORIOLIS.ErrorsNotOwnedItemForMacro")
    );
  const item = await fromUuid(documentData.uuid, false);
  if (!item || (item.type !== "weapon" && item.type !== "armor")) {
    return ui.notifications.warn(
      game.i18n.localize("YZECORIOLIS.ErrorsNoItemForMacro")
    );
  }
  // create the macro command.  Get an existing item macro if it exists.
  // Otherwise create a new one.
  const command = `game.yzecoriolis.rollItemMacro("${item.name}");`;
  let macro = game.macros.contents.find(
    (m) => m.name === item.name && m.command === command
  );
  if (!macro) {
    macro = await Macro.create({
      name: item.name,
      type: "script",
      img: item.img,
      command: command,
      scope: "actor",
      flags: { "yzecoriolis.itemMacro": true },
    });
  }
  game.user.assignHotbarMacro(macro, slot);
  return;
}

/**
 * Roll a macro item.
 * @param  {} itemName
 */
function rollItemMacro(itemName) {
  const speaker = ChatMessage.getSpeaker();
  let actor;
  if (speaker.token) actor = game.actors.tokens[speaker.token];
  if (!actor) actor = game.actors.get(speaker.actor);
  if (!actor) {
    return ui.notifications.warn(
      game.i18n.localize("YZECORIOLIS.ErrorsNoActorSelectedForMacro")
    );
  }
  // Get matching items
  const items = actor ? actor.items.filter((i) => i.name === itemName) : [];
  if (items.length > 1) {
    ui.notifications.warn(
      game.i18n.localize("YZECORIOLIS.ErrorsActorHasDuplicateItemsForMacro")
    );
  } else if (items.length === 0) {
    return ui.notifications.warn(
      game.i18n.localize("YZECORIOLIS.ErrorsActorNotHasItemForMacro")
    );
  }
  const item = items[0];

  // Trigger the item roll
  return item.roll();
}

**function rollActorMacro(rollName, rollType) {
  const speaker = ChatMessage.getSpeaker();
  let actor;
  if (speaker.token) actor = game.actors.tokens[speaker.token];
  if (!actor) actor = game.actors.get(speaker.actor);
  if (!actor) {
    return ui.notifications.warn(
      game.i18n.localize("YZECORIOLIS.ErrorsNoActorSelectedForMacro")
    );
  }
  
  return actor.roll(rollName, rollType, actor);
}**

**Comment by kbender84** [comment]
actor.js
[//token_action_hud addition
import { coriolisRoll, coriolisModifierDialog } from "../coriolis-roll.js";
/**
 * Extend the base Actor entity by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */

export class yzecoriolisActor extends Actor {
  /**
   * Augment the basic actor data with additional dynamic data.
   */
  prepareData() {
    super.prepareData();

    const actorData = this;

    // Make separate methods for each Actor type (character, npc, etc.) to keep
    // things organized.
    if (actorData.type === "character")
      this._prepareCharacterData(actorData, true);
    if (actorData.type === "npc") this._prepareCharacterData(actorData, false);
  }

  async _preCreate(initData, options, user) {
    await super._preCreate(initData, options, user);
    //setup default images for ships
    if (
      initData.type === "ship" &&
      hasProperty(initData, "img") &&
      initData.img === Actor.DEFAULT_ICON
    ) {
      this.updateSource({ img: CONFIG.YZECORIOLIS.DEFAULT_SHIP_KEY_ART });
    }

    // we check the incoming data to make sure we aren't overriding a 'cloning'
    // operation.
    if (
      !hasProperty(initData, "system.keyArt") &&
      (initData.type === "character" || initData.type === "npc")
    ) {
      this.updateSource({
        "system.keyArt": CONFIG.YZECORIOLIS.DEFAULT_PLAYER_KEY_ART,
      });
    }
    // if we have a blank string keyArt prop, just set it to the default.
    if (
      hasProperty(initData, "system.keyArt") &&
      (initData.type === "character" || initData.type === "npc") &&
      initData.system.keyArt === ""
    ) {
      this.updateSource({
        "system.keyArt": CONFIG.YZECORIOLIS.DEFAULT_PLAYER_KEY_ART,
      });
    }
  }

  async _onCreate(data, ...args) {
    await super._onCreate(data, ...args);
  }

  async _preUpdate(updateData, options, user) {
    await super._preUpdate(updateData, options, user);
  }
  /**
   * Prepare Character type specific data
   */
  _prepareCharacterData(actorData, capCharPoints) {
    const sysData = actorData.system;

    if (capCharPoints) {
      // Cap attribute scores
      Object.keys(sysData.attributes).forEach((k) => {
        let attr = sysData.attributes[k];
        if (attr.value > attr.max) {
          attr.value = attr.max;
        }
        if (attr.value < attr.min) {
          attr.value = attr.min;
        }
      });

      //Cap Skill scores
      Object.keys(sysData.skills).forEach((k) => {
        let skl = sysData.skills[k];
        if (skl.value > skl.max) {
          skl.value = skl.max;
        }
        if (skl.value < skl.min) {
          skl.value = skl.min;
        }
      });
    }

    let hpBonuses = this._prepHPBonuses();
    let mpBonuses = this._prepMPBonuses();
    sysData.hitPoints.max =
      sysData.attributes.strength.value +
      sysData.attributes.agility.value +
      hpBonuses;
    sysData.mindPoints.max =
      sysData.attributes.wits.value +
      sysData.attributes.empathy.value +
      mpBonuses;

    if (sysData.hitPoints.value > sysData.hitPoints.max) {
      sysData.hitPoints.value = sysData.hitPoints.max;
    }
    if (sysData.mindPoints.value > sysData.mindPoints.max) {
      sysData.mindPoints.value = sysData.mindPoints.max;
    }
  }

  _prepareChatRollOptions(template, title) {
    let chatOptions = {
      speaker: {
        alias: this.prototypeToken.name,
        actor: this._id,
      },
      title: title,
      template: template,
      rollMode: game.settings.get("core", "rollMode"),
      sound: CONFIG.sounds.dice,
      flags: {
        img: this.prototypeToken.randomImg
          ? this.img
          : this.prototypeToken.texture.src,
      },
      // img to be displayed next to the name on the test card - if it's a wildcard img, use the actor image
    };

    // If the test is coming from a token sheet
    if (this.token) {
      chatOptions.speaker.alias = this.token.name; // Use the token name instead of the actor name
      chatOptions.speaker.token = this.token._id;
      chatOptions.speaker.scene = canvas.scene._id;
      chatOptions.flags.img = this.token.texture.src; // Use the token image instead of the actor image
    } // If a linked actor - use the currently selected token's data if the actor id matches
    else {
      let speaker = ChatMessage.getSpeaker();
      if (speaker.actor == this._id) {
        chatOptions.speaker.alias = speaker.alias;
        chatOptions.speaker.token = speaker.token;
        chatOptions.speaker.scene = speaker.scene;
        chatOptions.flags.img = speaker.token
          ? canvas.tokens.get(speaker.token).document.texture.src
          : chatOptions.flags.img;
      }
    }

    return chatOptions;
  }

  _prepHPBonuses() {
    // look through talents for any HPBonuses
    let bonus = 0;
    for (let t of this.items) {
      if (t.type !== "talent") {
        continue;
      }
      const tData = t.system;
      bonus += Number(tData.hpBonus);
    }
    return bonus;
  }

  _prepMPBonuses() {
    // look through talents for any MPBonuses
    let bonus = 0;
    for (let t of this.items) {
      if (t.type !== "talent") {
        continue;
      }
      const tData = t.system;
      bonus += Number(tData.mpBonus);
    }
    return bonus;
  }

  /** @override */
  static async create(initData, options = {}) {
    initData.prototypeToken = initData.prototypeToken || {};
    if (initData.type === "character" || initData.type === "npc") {
      foundry.utils.mergeObject(
        initData.prototypeToken,
        {
          actorLink: true,
        },
        { overwrite: false }
      );
    }
    return super.create(initData, options);
  }

  //token_action_hud addition
    async roll(skillName,inputRollType, actorData) {
    //const item = this.actor.system.attributes.wits: null;
	console.log('debug');
	console.log(skillName);
	console.log(inputRollType);
    console.log(actorData.system);
	const actor = actorData;
	let attributeForSkill= 'wits';
	switch (skillName){
					  case 'technology' :
					  case 'dataDjinn' :
					  case 'science' :
					  case 'medicurgy' :
					  case 'observation' :
					  case 'survival' :
					  attributeForSkill= 'wits';
					  break;
					  case 'manipulation' :
					  case 'command' : 
					  case 'mysticPowers' :
					  case 'culture' :
					  attributeForSkill= 'empathy';
					  break;
					  case 'dexterity' :
					  case 'infiltration' :
					  case 'rangedCombat' :
					  case 'pilot' :
					  attributeForSkill= 'agility';
					  break;
					  case 'meleeCombat' :
					  case 'force' :
					  attributeForSkill= 'strength';
					  break;
					}
	let rollData;
	
	switch (inputRollType) {
			case 'attribute':
                rollData = {
				  actorType: actorData.type,
				  rollType: inputRollType,
				  attributeKey: skillName,
				  attribute: actorData.system.attributes[skillName].value, 
				  modifier: 0,
				  bonus: 0,
				  rollTitle: game.i18n.localize(`YZECORIOLIS.Attr${skillName.capitalize()}`)+' Roll', 
				  pushed: false
				};
				break;
			case 'general' :
			case 'advanced' :
                rollData = {
					//{rollType, skill, attribute, modifier} rollData
					//attributes[rollData.attributeKey]
				  actorType: actorData.type,
				  rollType: inputRollType,
				  attributeKey: attributeForSkill,
				  attribute: actorData.system.attributes[attributeForSkill].value, 
			      skillKey: skillName.toLowerCase(),
			      skill: actorData.system.skills[skillName.toLowerCase()].value,//dataset.skillkey ? actorData.skills[dataset.skillkey].value : 0,
				  modifier: 0,
				  bonus: 0,
				  rollTitle: game.i18n.localize(`YZECORIOLIS.Skill${skillName.capitalize()}`)+' Roll', //import nice name
				  pushed: false
				  //features: item?.special ? Object.values(item.special).join(", ") : "",
				};
			break;
			
	}
	
    const chatOptions = actor._prepareChatRollOptions(
      "systems/yzecoriolis/templates/sidebar/roll.html",
     inputRollType
    );

    coriolisModifierDialog((modifier, additionalData) => {
      rollData.modifier = modifier;
      rollData.additionalData = additionalData;
      coriolisRoll(chatOptions, rollData);
    }, false);
    
  }
  
  
}





](url)

**Comment by IrishWolf** [comment]
> I've developed token-action-hud for Coriolis, but to work properly it requires additional functions in yzecoriolis.js and actor.js I have the code, can it be added to the new release of the core system?

Hey @kbender84, if it works there should be a way. :)

Would it be possible for you to make an branch of this git and a pull-request? That would make things easier for us to check as GitHub formats your code in the comments here and it is additional work to sort that out.
If thats not possible for you, can you at least post you code in something like [Pastebin](https://pastebin.com/)?

**Comment by kbender84** [comment]
Branch. Pull request. Sure. Let me try.

**Comment by kbender84** [comment]
I didn't have write access to publish new branch on winks-vtt yze-coriolis, so I've cloned repository and created a fork on my repo
https://github.com/kbender84/yze-coriolis

**Comment by IrishWolf** [comment]
> Hi @IrishWolf , I didn't have write access to publish new branch on winks-vtt yze-coriolis, so I've cloned repository and created a fork on my repo
> https://github.com/kbender84/yze-coriolis

Hmm, everyone should be able to make a pull request. 🤔

I'm currently sick, so I can't/won't check further. Maybe in the next days.

**Comment by kbender84** [comment]
Sure. No worries. Take care!

**Comment by kbender84** [comment]
The pull request is still waiting for review :) https://github.com/winks-vtt/yze-coriolis/pull/244

**Comment by kbender84** [comment]
Solved in on my side, not needed anymore
