### ISSUE TITLE
Custom icons not displayed in item sheet

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#24]
When custom icon is selected for an item, it is not visualized in the Items tab. Image attached. 

![Screenshot 2020-09-13 105523](https://user-images.githubusercontent.com/63558984/93013291-ca47b380-f5af-11ea-9033-5983d629fa21.jpg)

**Comment by AlexOkafor** [comment]
@r-valyar I'm not able to reproduce this. What image format is that icon and what are the dimensions?
![image](https://user-images.githubusercontent.com/45021773/93048122-218b6980-f62c-11ea-9c05-38a425a02b45.png)

**Comment by r-valyar** [comment]
@AlexOkafor  I am using the icons from the game-icons.net content pack.

**Comment by AlexOkafor** [comment]
@r-valyar I'd recommend until I get a fix out for this to download those icons as svg instead of png to work around it.
