### ISSUE TITLE
Pushing Roll Doesn't Work as Expected in Foundry v11

### ISSUE THREAD

**Issue by JTThurn** [winks-vtt/yze-coriolis#246]
Two issues have popped up since upgrading to Foundry V11. This is without any modules enabled.

When a player rolls and wants to pray to the icons the button does not work. If the GM tries to push a _player_ roll it sorta works (see second issue below). But if the GM tries to push their _own_ roll, it doesn't work. I don't know Javascript at all, so the best I can do is show a screenshot of the console result when someone clicks the button.

![image](https://github.com/winks-vtt/yze-coriolis/assets/34930763/7ab9b6d0-6f36-44ee-a888-cb7170ffaaf0)

The second issue is when the GM clicks to push a player roll. The 3D dice show, but nothing updates in the chat itself. It remains static.

![image](https://github.com/winks-vtt/yze-coriolis/assets/34930763/60f56daf-a64b-4474-ada4-5d96d61004de)

**Comment by IrishWolf** [comment]
The system (and the modules from FL) isn't released for v11 so you will probably get even more errors like this. :/

**Comment by AlexOkafor** [comment]
@JTThurn Thanks for the heads up! I've updated the system and it should be working now.
