### ISSUE TITLE
encumbrance can not be adjusted

### ISSUE THREAD

**Issue by lektu** [winks-vtt/yze-coriolis#249]
Currently, having a cyberimplant like _Endo Skeleton_ does not double the carrying capacity. I understand that's because items have defined bonuses (HP, MP) and are not special cased. In some cases it wouldn't even make sense because some bonuses are not fixed and depend on narrative decisions (like the Endo Skeleton +2 to Force for heavy lifting). But in this case it is a fixed value that doesn't depend on external circumstances, so it'd be useful to have it reflected in the character sheet.

The problem is that there's no way to change it manually (in the charsheet), because encumbrance is always computed directly from Strength.

**Comment by IrishWolf** [comment]
Would be fixxed with #235

**Comment by lektu** [comment]
Any idea whether this will be fixed at some point?

**Comment by IrishWolf** [comment]
Would be part of the new pull #258 
Fairly good chance it will see the light of the day this time :D
