### ISSUE TITLE
Cannot create compendium with certain name

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#25]
I encountered weird issue - certain names are not accepted as compendium items and error message states that such name already exists, while the world is completely new. I have tested the names listed below, as I am creating compendium packs for talents:

General
General Talents
Icons
Free Traders
Humanite
Humanite Talents
Mystical Powers
Mystical Powers Talents

![general](https://user-images.githubusercontent.com/63558984/93050484-a34eb780-f66b-11ea-8a03-71a2429a3eb8.jpg)
![icon](https://user-images.githubusercontent.com/63558984/93050488-a5b11180-f66b-11ea-9b34-d334377c274f.jpg)

**Comment by AlexOkafor** [comment]
I couldn't seem to isolate this to anything in my code, but updating to Alpha channel seemed to have fixed it? Once I updated and then just reverted back to stable (0.6.6) I was able to create whatever compendiums I wanted.

Going to recommend sitting tight for the next foundry update to resolve this, or if you feel like updating to alpha and then going back, you can.
