### ISSUE TITLE
Feature suggestion - implement zero/none weight

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#26]
All my players carry items that have no weight (as they are big computers and labs, but use them to make rolls and have them assigned to them). I suggest to implement zero/none weight that will address this and won't interfere with the proper weight calculation.

**Comment by AlexOkafor** [comment]
@r-valyar According to the Coriolis system (p 104), this seems to be the function of the 'Tiny weight' and that is how it's currently implemented. That is a current work around. But I do recognize that the rulebook makes a distinction between 'tiny' and '-'. I'll add that to avoid confusion.
