### ISSUE TITLE
v12 compatibility is not full

### ISSUE THREAD

**Issue by Furukia** [winks-vtt/yze-coriolis#276]
There is a bug that doesn't allow to create an item, because item creation dialog is not rendered at all.
![image](https://github.com/user-attachments/assets/90f3a00f-7eb2-46fd-b9a4-3dba5857a248)
![image](https://github.com/user-attachments/assets/e12fb117-a6e4-4b2f-ae24-6106d90d1521)
It's not rendered because `game.system.documentTypes.Item` is an Object now, and before v12 it was probably an Array.

Tested on a fresh world with no modules.

**Comment by AlexOkafor** [comment]
version 3.9.1 should address this (300aed936acde1001a23c97c6635594204812a5b)
