### ISSUE TITLE
Enhancement - Implement button to mark not carried items that are taken out of encumbrance calculation

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#28]
Players are often putting into their inventory items that are carried in ship or somewhere else. Therefore they are considered part of their character's inventory but not really carried at the moment. I suggest to implement new button next to the "Carried" one or actually transform the existing button with the following behavior:

- When the button is pressed the weight is not calculated against the encumbrance limits. 
- Button will visually indicate which item is not carried

Good example is Fantasy Grounds. The implementation is heavily used in every ruleset:

![Screenshot 2020-09-17 123622](https://user-images.githubusercontent.com/63558984/93453518-73f5b000-f8e2-11ea-878b-44b61f8df5fd.jpg)

**Comment by AlexOkafor** [comment]
resolved in https://github.com/winks-vtt/yze-coriolis/pull/154
