### ISSUE TITLE
All  Coriolis modules fail on import actor

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#282]
Importing content from core rulebook results in countless errors related to non-existing actors:
![image](https://github.com/user-attachments/assets/208ce8c6-183b-4f0a-ac98-87977fad161f)
The actors seem created, but it is not clear what errors can cause underneath. 

Foundry version & system:
![image](https://github.com/user-attachments/assets/fe6ff88c-08b6-4d1d-947e-734da531c064)

**Comment by kylania** [comment]
Same happened to me.  With the Core Rulebook those errors continued to be generated every few seconds until i created a new Actor.  Dragging an existing Actor onto a Scene did not stop them.

With the Last Voyage Module they seemed to happen after I changed Scenes.

**Comment by AlexOkafor** [comment]
working on the system-side fixes this week. Modules will soon follow.
