### ISSUE TITLE
Actor Importing fails

### ISSUE THREAD

**Issue by StorytellerTrev** [winks-vtt/yze-coriolis#283]
I have tried Core system Coriolis V12 and V11 but get the same issues when importing any module of Coriolis

![Screenshot_2024-09-13_at_6 09 35_am](https://github.com/user-attachments/assets/67a5c920-24ee-4d26-80cc-d15f0cd6f923)

**Comment by AlexOkafor** [comment]
Yep, a fix is in the works. Need to make updates to both systems and the modules.
System fix is pending (in the next hour or so).
