### ISSUE TITLE
Dice So Nice Rolling Twice

### ISSUE THREAD

**Issue by chewey57** [winks-vtt/yze-coriolis#284]
When Dice So Nice (DsN) module is enabled, dice are rendered twice when rolling from a sheet. Issue was initially opened with DsN and received the following response:

"It looks like they are calling Dice So Nice manually AND automatically.

I'm not sure why; maybe they recently modified how they render their rolls and made it compatible with the DsN auto-detection of rolls unbeknownst to them.

They should probably remove the manual call to DsN."

Steps to reproduce:
1. Open character sheet
2. Select skill to roll
3. Roll

Foundry Version: v12 Build 331
Coriolis Version: 3.9.1

**Comment by ImNotYourBudde** [comment]
Wanting to note that this is still happening as of 3.9.3 Coriolis Version

**Comment by Alis-72** [comment]
This was discussed briefly in DsN gitlab too. Some idea how to fix was mentioned
https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues/445

**Comment by lektu** [comment]
It sort of works if you comment out the call to showDiceSoNice in coriolisRoll (line 30 of coriolis-roll.js), in the sense that normal rolls show the dice just once, and rerolls (which need the API) still work too.

But it should be tested for other things, like hidden rolls, etc.

**Comment by kbender84** [comment]
Thanks, commenting out the manual call to dice so nice worked the trick for me.

**Comment by AlexOkafor** [comment]
@lektu Thank you for the PR for this!
