### ISSUE TITLE
Bug - scroll issue when adjusting item order/count/equipped statte

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#30]
There is bug related to scroll bar reset position after adjustments of count/order/state of an iteam.

![scroll_bug](https://user-images.githubusercontent.com/63558984/93459344-3eed5b80-f8ea-11ea-9c77-3aad0ee2599a.gif)

**Comment by AlexOkafor** [comment]
@r-valyar In the latest version (1.4.1) this has (finally) been addressed. Thanks for creating the issue!
