### ISSUE TITLE
Items on Macrobar have incorrect dice rolls

### ISSUE THREAD

**Issue by Necrot1c** [winks-vtt/yze-coriolis#32]
When dragging an item from the Actor items onto the macro bar, it doesn't keep the icon and the macro it creates is incorrect.
![image](https://user-images.githubusercontent.com/66018435/94031105-6ba3e600-fdb6-11ea-8781-810b3525485f.png)
![image](https://user-images.githubusercontent.com/66018435/94031334-a4dc5600-fdb6-11ea-90da-713d36c41c88.png)

**Comment by AlexOkafor** [comment]
Currently, dragging/dropping into the hotbar for items isn't fully supported. It is on the short list of quality of life fixes I want to attend to after the ship sheet.

**Comment by AlexOkafor** [comment]
Item macros appear to be working from a previous release.
