### ISSUE TITLE
All Dice rolls fail and the language changes to spanish

### ISSUE THREAD

**Issue by Onioninblack** [winks-vtt/yze-coriolis#34]
![image](https://user-images.githubusercontent.com/69573380/99195516-9131e800-2786-11eb-9c54-ece31cb7a1c9.png)

All rolls fail, no matter how many times I roll dice. If I use Dice so nice I can see they are a lot of 6s, but the program doesn't detect them.
Also, the language is Spanish for default and there is no option to modify it.

**Comment by AlexOkafor** [comment]
@Onioninblack What is your language setting when you go to configure your settings?
![image](https://user-images.githubusercontent.com/45021773/100953816-4e3f7680-34e1-11eb-99f2-f98855b5dc79.png)

Which version of Foundry are you on?

**Comment by Onioninblack** [comment]
Hi Alex, I forgot to post the new info.
I erased the folder at the pc and reinstalled it and it worked ok.
A friend of mine had the same issue, but he has solved it too.

Congratulations on your work, by the way. It's one of the most beautiful and useful sheets I have tried.
