### ISSUE TITLE
Portrait doesn't show in the sidebar (but token does?)

### ISSUE THREAD

**Issue by jomblr** [winks-vtt/yze-coriolis#35]
Portraits doesn't show up properly in the sidebar, while tokens do. If this is by intent, it breaks the actors when using wildcard portraits (see images)

![image](https://user-images.githubusercontent.com/9035575/100140084-c0381000-2e90-11eb-8113-ed3fdf1b6a0e.png)

![image](https://user-images.githubusercontent.com/9035575/100140389-2ae94b80-2e91-11eb-91e9-4afc1e8dbe72.png)

**Comment by AlexOkafor** [comment]
Thanks for the heads up. I wasn't aware of this feature :). Will investigate. For the time being, token image path is taken literally, so wildcards aren't supported.

**Comment by coderunner** [comment]
@jomblr this should be fixed in the latest release.

**Comment by coderunner** [comment]
@AlexOkafor I think we can close this.
