### ISSUE TITLE
Support permanent stress reductions

### ISSUE THREAD

**Issue by AlexOkafor** [winks-vtt/yze-coriolis#37]
some die rolls can permanently damage a person's max mind points pool. need to add a tracker to that.

**Comment by jomblr** [comment]
Some of the characters in the Mercy of the Icons have talents which increases stresspoints. Maybe add a config page on the character sheet for mods like these?

**Comment by AlexOkafor** [comment]
@jomblr ya I suspect I may do something similar to what the AlienRPG system does and just has a tab for each item called 'mods' that let's you modify certain aspects (plus or minus)
