### ISSUE TITLE
Change initiative roll to d66

### ISSUE THREAD

**Issue by AlexOkafor** [winks-vtt/yze-coriolis#40]
Currently it's just a 1d6. Refer to rulebook to see if I can do rolls as close as possible to ruleset vs foundry's default combat system.

**Comment by jomblr** [comment]
Isn't 1d6 correct though?

> All participants in a fight, willing or unwilling, **roll one die each**. The result of each die is the initiative score for that person.

**Comment by AlexOkafor** [comment]
@jomblr I think I misunderstood the  original request from discord. This was intended for tie-breakers. Will consult rulebook to see the ruling on this. It may have just been a 'house rule' request.

**Comment by AlexOkafor** [comment]
Yep, confirmed, ties are just a re-roll of another die. doesn't really need to be d66.
