### ISSUE TITLE
Icons randomly reverted to Foundry Default

### ISSUE THREAD

**Issue by DanieleSuppo** [winks-vtt/yze-coriolis#44]
When the player sheet is edited, the default Coriolis icon randomly revert to the "deafult mistery man" of Foundry.
If you refresh the page, everything is back to normal.

How to reproduce:
- create a new character sheet, add few items then try to edit / delete a line

![immagine](https://user-images.githubusercontent.com/2264815/115972963-f79b0d80-a551-11eb-9169-06b8340902e1.png)

**Comment by AlexOkafor** [comment]
In the latest version (on FVTT 0.8.6) this doesn't seem to be occurring anymore as I can't reproduce it. Please feel free to re-open if you encounter this again on the latest.
