### ISSUE TITLE
Restricted items in Actor sheet

### ISSUE THREAD

**Issue by SesuUisu** [winks-vtt/yze-coriolis#5]
Hey,

when the box for restricted items is checked, it is only be shown in the actor sheet for gear, not for weapons, explosives or armor.

**Comment by AlexOkafor** [comment]
@SesuUisu This was a data layout issue. There were fields I had deemed more important than 'restricted' in those categories that I figured would be more useful for "at a glance". I think to make it more consistent I may make 'Restricted' just a small display slug when you fold out the item like 'Single-Shot':

![image](https://user-images.githubusercontent.com/45021773/93171709-9a0b2c80-f6f7-11ea-882a-380a9ffca510.png)

**Comment by SesuUisu** [comment]
This solution sounds good to me.
