### ISSUE TITLE
Add a New Chat Message for when an Actor uses a weapon that displays the weapons stats - Chat Message

### ISSUE THREAD

**Issue by KodKoftan** [winks-vtt/yze-coriolis#60]
As in the title i believe that it would be beneficial for the GM to have the weapon stats displayed in the chat when rolling for weapons.

**Comment by taranion** [comment]
I really would like that too. Including the possibility to roll on a critical hit table - or at least a d100, if it was a crit.

**Comment by KodKoftan** [comment]
@taranion don't know how this would work. You need to create the critical injuries yourself and then make your own table as this does not exist in foundry and is something you buy yourself. I believe that the best way is just to make the table and drag it to the macrobar.

**Comment by taranion** [comment]
True, without a table provided by the game system itself, a crit button would simply initiate a D100 roll (and eventually ask for a modifier).

**Comment by AlexOkafor** [comment]
addressed in https://github.com/winks-vtt/yze-coriolis/pull/174
