### ISSUE TITLE
Setting Ship weapon ammo forces left most module to disabled

### ISSUE THREAD

**Issue by Zeddican** [winks-vtt/yze-coriolis#96]
Adding any ammo count to a ship weapon module sets the left most module to disabled and it cannot be changed. 

Recreation steps:

1. add a module - any kind 
2. add a weapon module
3. set the weapon module ammo count to a value other than 1, press enter to accept
4. Left most module is then disabled and cannot be changed.

**Comment by AlexOkafor** [comment]
Thanks for the report! Fixed in 2.1.9.
